import { NewsItem, Persona } from './types';
import * as Personas from './personas';

export type RawCountryData = {
    id: string;
    name: string;
    avatar: string;
    continent: string;
    tier: 1 | 2 | 3;
    persona?: Persona;
    profile: string;
    detailedProfile: string;
    motto: string;
    established: string;
    nationalDay: string;
    newYear: string;
    language: string;
    ethnic_groups: string[];
};

export const RAW_COUNTRIES: Record<string, RawCountryData> = {
    'AFG': { id: 'AFG', name: 'Afghanistan', avatar: '🇦🇫', continent: 'Asia', tier: 3, persona: Personas.AFG_PERSONA, profile: 'A landlocked country at the crossroads of Central and South Asia...', detailedProfile: 'Afghanistan has a long history...', motto: 'لا إله إلا الله، محمد رسول الله', established: 'August 19, 1919', nationalDay: 'August 19', newYear: 'Nowruz (March 21)', language: 'Pashto, Dari', ethnic_groups: ['Pashtun', 'Tajik', 'Hazara', 'Uzbek'] },
    'ALB': { id: 'ALB', name: 'Albania', avatar: '🇦🇱', continent: 'Europe', tier: 3, persona: Personas.ALB_PERSONA, profile: 'A Balkan nation with a unique language...', detailedProfile: 'Albania is known for its archaeological sites...', motto: 'Ti Shqipëri, më jep nder, më jep emrin Shqipëtar', established: 'November 28, 1912', nationalDay: 'November 28', newYear: 'January 1', language: 'Albanian', ethnic_groups: ['Albanian'] },
    'DZA': { id: 'DZA', name: 'Algeria', avatar: '🇩🇿', continent: 'Africa', tier: 2, persona: Personas.DZA_PERSONA, profile: 'A vast North African country...', detailedProfile: 'Algeria is the largest country in Africa...', motto: 'بالشّعب وللشّعب', established: 'July 5, 1962', nationalDay: 'November 1', newYear: 'January 1', language: 'Arabic, Tamazight', ethnic_groups: ['Arab-Berber'] },
    'AND': { id: 'AND', name: 'Andorra', avatar: '🇦🇩', continent: 'Europe', tier: 3, persona: Personas.AND_PERSONA, profile: 'A tiny, independent principality...', detailedProfile: 'Andorra is a microstate known for its ski resorts...', motto: 'Virtus Unita Fortior', established: '1278', nationalDay: 'September 8', newYear: 'January 1', language: 'Catalan', ethnic_groups: ['Andorran', 'Spanish', 'Portuguese', 'French'] },
    'AGO': { id: 'AGO', name: 'Angola', avatar: '🇦🇴', continent: 'Africa', tier: 3, persona: Personas.AGO_PERSONA, profile: 'A southern African nation...', detailedProfile: 'Angola is a major oil producer...', motto: 'Virtus Unita Fortior', established: 'November 11, 1975', nationalDay: 'November 11', newYear: 'January 1', language: 'Portuguese', ethnic_groups: ['Ovimbundu', 'Mbundu', 'Bakongo'] },
    'ARG': { id: 'ARG', name: 'Argentina', avatar: '🇦🇷', continent: 'South America', tier: 2, persona: Personas.ARG_PERSONA, profile: 'A large South American nation...', detailedProfile: 'Argentina is famous for tango, beef, and football...', motto: 'En Unión y Libertad', established: 'July 9, 1816', nationalDay: 'May 25', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['European descent (mostly Spanish and Italian)', 'Mestizo'] },
    'ARM': { id: 'ARM', name: 'Armenia', avatar: '🇦🇲', continent: 'Asia', tier: 3, persona: Personas.ARM_PERSONA, profile: 'A nation in the mountainous Caucasus region...', detailedProfile: 'Armenia is a landlocked country with a rich, ancient culture...', motto: 'Մի ասպետ, մեկ ազգ, մեկ մշակույթ', established: 'September 21, 1991', nationalDay: 'September 21', newYear: 'January 1', language: 'Armenian', ethnic_groups: ['Armenian'] },
    'AUS': { id: 'AUS', name: 'Australia', avatar: '🇦🇺', continent: 'Oceania', tier: 2, persona: Personas.AUS_PERSONA, profile: 'A continent-country known for its vast outback...', detailedProfile: 'Australia is a developed country with a market-based economy...', motto: 'N/A (unofficially "Advance Australia")', established: 'January 1, 1901', nationalDay: 'January 26', newYear: 'January 1', language: 'English', ethnic_groups: ['English', 'Australian', 'Irish', 'Scottish', 'Chinese'] },
    'AUT': { id: 'AUT', name: 'Austria', avatar: '🇦🇹', continent: 'Europe', tier: 2, persona: Personas.AUT_PERSONA, profile: 'A landlocked country of Central Europe...', detailedProfile: 'Austria is renowned for its classical music legacy...', motto: 'N/A', established: '1955 (Modern State)', nationalDay: 'October 26', newYear: 'January 1', language: 'German', ethnic_groups: ['Austrian', 'German', 'Turkish', 'Serbian'] },
    'AZE': { id: 'AZE', name: 'Azerbaijan', avatar: '🇦🇿', continent: 'Asia', tier: 3, persona: Personas.AZE_PERSONA, profile: 'The Land of Fire, a nation and former Soviet republic...', detailedProfile: 'Azerbaijan has a large and growing economy...', motto: 'N/A', established: 'October 18, 1991', nationalDay: 'May 28', newYear: 'Nowruz (March 20 or 21)', language: 'Azerbaijani', ethnic_groups: ['Azerbaijani', 'Lezgin', 'Russian', 'Armenian'] },
    'BHS': { id: 'BHS', name: 'Bahamas', avatar: '🇧🇸', continent: 'North America', tier: 3, persona: Personas.BHS_PERSONA, profile: 'A coral-based archipelago in the Atlantic Ocean...', detailedProfile: 'The Bahamas is a popular tourist destination...', motto: 'Forward, Upward, Onward, Together', established: 'July 10, 1973', nationalDay: 'July 10', newYear: 'January 1', language: 'English', ethnic_groups: ['Afro-Bahamian', 'European', 'Mixed'] },
    'BHR': { id: 'BHR', name: 'Bahrain', avatar: '🇧🇭', continent: 'Asia', tier: 3, persona: Personas.BHR_PERSONA, profile: 'A small island country in the Persian Gulf...', detailedProfile: 'Bahrain was one of the first Gulf states to discover oil...', motto: 'بحريننا (Our Bahrain)', established: 'August 15, 1971', nationalDay: 'December 16', newYear: 'January 1', language: 'Arabic', ethnic_groups: ['Bahraini', 'Asian', 'other Arab'] },
    'BGD': { id: 'BGD', name: 'Bangladesh', avatar: '🇧🇩', continent: 'Asia', tier: 2, persona: Personas.BGD_PERSONA, profile: 'A South Asian country marked by lush greenery...', detailedProfile: 'Bangladesh is one of the world\'s most densely populated countries...', motto: 'N/A', established: 'March 26, 1971', nationalDay: 'March 26', newYear: 'Pohela Boishakh (April 14)', language: 'Bengali', ethnic_groups: ['Bengali'] },
    'BRB': { id: 'BRB', name: 'Barbados', avatar: '🇧🇧', continent: 'North America', tier: 3, profile: 'An eastern Caribbean island...', detailedProfile: 'Barbados is known for its tropical beaches...', motto: 'Pride and Industry', established: 'November 30, 1966', nationalDay: 'November 30', newYear: 'January 1', language: 'English', ethnic_groups: ['African descent', 'White', 'Mixed'] },
    'BLR': { id: 'BLR', name: 'Belarus', avatar: '🇧🇾', continent: 'Europe', tier: 3, persona: Personas.BLR_PERSONA, profile: 'A landlocked country in Eastern Europe...', detailedProfile: 'Belarus has an economy that remains largely state-controlled...', motto: 'N/A', established: 'August 25, 1991', nationalDay: 'July 3', newYear: 'January 1', language: 'Belarusian, Russian', ethnic_groups: ['Belarusian', 'Russian', 'Polish'] },
    'BEL': { id: 'BEL', name: 'Belgium', avatar: '🇧🇪', continent: 'Europe', tier: 2, profile: 'A country in Western Europe...', detailedProfile: 'Belgium is culturally and linguistically divided...', motto: 'L\'union fait la force', established: 'October 4, 1830', nationalDay: 'July 21', newYear: 'January 1', language: 'Dutch, French, German', ethnic_groups: ['Flemish', 'Walloon', 'German'] },
    'BLZ': { id: 'BLZ', name: 'Belize', avatar: '🇧🇿', continent: 'North America', tier: 3, persona: Personas.BLZ_PERSONA, profile: 'A nation on the eastern coast of Central America...', detailedProfile: 'Belize is home to the massive Belize Barrier Reef...', motto: 'Sub Umbra Floreo', established: 'September 21, 1981', nationalDay: 'September 21', newYear: 'January 1', language: 'English', ethnic_groups: ['Mestizo', 'Creole', 'Maya', 'Garifuna'] },
    'BEN': { id: 'BEN', name: 'Benin', avatar: '🇧🇯', continent: 'Africa', tier: 3, persona: Personas.BEN_PERSONA, profile: 'A French-speaking West African nation...', detailedProfile: 'The Republic of Benin was formerly known as Dahomey...', motto: 'Fraternité, Justice, Travail', established: 'August 1, 1960', nationalDay: 'August 1', newYear: 'January 1', language: 'French', ethnic_groups: ['Fon', 'Adja', 'Yoruba', 'Bariba'] },
    'BTN': { id: 'BTN', name: 'Bhutan', avatar: '🇧🇹', continent: 'Asia', tier: 3, persona: Personas.BTN_PERSONA, profile: 'A Buddhist kingdom on the Himalayas’ eastern edge...', detailedProfile: 'Bhutan is a carbon-negative country...', motto: 'N/A', established: 'December 17, 1907', nationalDay: 'December 17', newYear: 'Losar (Varies)', language: 'Dzongkha', ethnic_groups: ['Ngalop', 'Lhotshampa', 'Sharchop'] },
    'BOL': { id: 'BOL', name: 'Bolivia', avatar: '🇧🇴', continent: 'South America', tier: 3, persona: Personas.BOL_PERSONA, profile: 'A country in central South America...', detailedProfile: 'Bolivia is one of two landlocked countries in South America...', motto: 'La Unión es la Fuerza', established: 'August 6, 1825', nationalDay: 'August 6', newYear: 'January 1', language: 'Spanish, Quechua, Aymara', ethnic_groups: ['Mestizo', 'Quechua', 'Aymara', 'White'] },
    'BIH': { id: 'BIH', name: 'Bosnia & Herzegovina', avatar: '🇧🇦', continent: 'Europe', tier: 3, persona: Personas.BIH_PERSONA, profile: 'A country on the Balkan Peninsula...', detailedProfile: 'Bosnia and Herzegovina has a complex political structure...', motto: 'N/A', established: 'March 1, 1992', nationalDay: 'November 25', newYear: 'January 1', language: 'Bosnian, Croatian, Serbian', ethnic_groups: ['Bosniak', 'Serb', 'Croat'] },
    'BWA': { id: 'BWA', name: 'Botswana', avatar: '🇧🇼', continent: 'Africa', tier: 3, persona: Personas.BWA_PERSONA, profile: 'A landlocked country in Southern Africa...', detailedProfile: 'Botswana is known for its political stability...', motto: 'Pula (Rain)', established: 'September 30, 1966', nationalDay: 'September 30', newYear: 'January 1', language: 'English, Tswana', ethnic_groups: ['Tswana', 'Kalanga', 'Basarwa'] },
    'BRA': { id: 'BRA', name: 'Brazil', avatar: '🇧🇷', continent: 'South America', tier: 2, persona: Personas.BRA_PERSONA, profile: 'The largest country in South America...', detailedProfile: 'Brazil is a diverse country...', motto: 'Ordem e Progresso', established: 'September 7, 1822', nationalDay: 'September 7', newYear: 'January 1', language: 'Portuguese', ethnic_groups: ['White', 'Pardo (Mixed)', 'Black', 'Asian'] },
    'BRN': { id: 'BRN', name: 'Brunei', avatar: '🇧🇳', continent: 'Asia', tier: 3, persona: Personas.BRN_PERSONA, profile: 'A tiny nation on the island of Borneo...', detailedProfile: 'Brunei Darussalam is governed by an absolute monarchy...', motto: 'الدائمون المحسنون بالهدى', established: 'January 1, 1984', nationalDay: 'February 23', newYear: 'January 1', language: 'Malay', ethnic_groups: ['Malay', 'Chinese'] },
    'BGR': { id: 'BGR', name: 'Bulgaria', avatar: '🇧🇬', continent: 'Europe', tier: 3, persona: Personas.BGR_PERSONA, profile: 'A Balkan nation with diverse terrain...', detailedProfile: 'Bulgaria has a rich cultural heritage...', motto: 'Съединението прави силата', established: '681 AD', nationalDay: 'March 3', newYear: 'January 1', language: 'Bulgarian', ethnic_groups: ['Bulgarian', 'Turkish', 'Romani'] },
    'BFA': { id: 'BFA', name: 'Burkina Faso', avatar: '🇧🇫', continent: 'Africa', tier: 3, persona: Personas.BFA_PERSONA, profile: 'A landlocked country in West Africa...', detailedProfile: 'Burkina Faso, meaning "Land of Incorruptible People"...', motto: 'Unité, Progrès, Justice', established: 'August 5, 1960', nationalDay: 'December 11', newYear: 'January 1', language: 'French', ethnic_groups: ['Mossi', 'Fula', 'Gurunsi'] },
    'BDI': { id: 'BDI', name: 'Burundi', avatar: '🇧🇮', continent: 'Africa', tier: 3, persona: Personas.BDI_PERSONA, profile: 'A landlocked country in the Great Rift Valley...', detailedProfile: 'Burundi is one of the smallest countries in Africa...', motto: 'Unité, Travail, Progrès', established: 'July 1, 1962', nationalDay: 'July 1', newYear: 'January 1', language: 'Kirundi, French', ethnic_groups: ['Hutu', 'Tutsi', 'Twa'] },
    'KHM': { id: 'KHM', name: 'Cambodia', avatar: '🇰🇭', continent: 'Asia', tier: 3, persona: Personas.KHM_PERSONA, profile: 'A Southeast Asian nation...', detailedProfile: 'Cambodia has a rich history, most notably the Khmer Empire...', motto: 'ชาติ សាសនា ព្រះមហាក្សัตริย์', established: 'November 9, 1953', nationalDay: 'November 9', newYear: 'Chaul Chnam Thmey (April 13/14)', language: 'Khmer', ethnic_groups: ['Khmer'] },
    'CMR': { id: 'CMR', name: 'Cameroon', avatar: '🇨🇲', continent: 'Africa', tier: 3, persona: Personas.CMR_PERSONA, profile: 'A country in Central Africa...', detailedProfile: 'Cameroon is home to over 200 different linguistic groups...', motto: 'Paix, Travail, Patrie', established: 'January 1, 1960', nationalDay: 'May 20', newYear: 'January 1', language: 'French, English', ethnic_groups: ['Highlanders', 'Coastal Bantu', 'Kirdi'] },
    'CAN': { id: 'CAN', name: 'Canada', avatar: '🇨🇦', continent: 'North America', tier: 1, persona: Personas.CAN_PERSONA, profile: 'A vast North American country...', detailedProfile: 'Canada is the second-largest country by area...', motto: 'A Mari Usque Ad Mare', established: 'July 1, 1867', nationalDay: 'July 1', newYear: 'January 1', language: 'English, French', ethnic_groups: ['Canadian', 'English', 'Scottish', 'French', 'Irish'] },
    'CAF': { id: 'CAF', name: 'Central African Republic', avatar: '🇨🇫', continent: 'Africa', tier: 3, persona: Personas.CAF_PERSONA, profile: 'A landlocked country in Central Africa...', detailedProfile: 'Despite its significant mineral deposits...', motto: 'Unité, Dignité, Travail', established: 'August 13, 1960', nationalDay: 'December 1', newYear: 'January 1', language: 'French, Sango', ethnic_groups: ['Baya', 'Banda', 'Mandjia', 'Sara'] },
    'TCD': { id: 'TCD', name: 'Chad', avatar: '🇹🇩', continent: 'Africa', tier: 3, profile: 'A landlocked country in north-central Africa...', detailedProfile: 'Chad has a history of political turmoil...', motto: 'Unité, Travail, Progrès', established: 'August 11, 1960', nationalDay: 'August 11', newYear: 'January 1', language: 'French, Arabic', ethnic_groups: ['Sara', 'Arab', 'Kanembu/Bornu/Buduma'] },
    'CHL': { id: 'CHL', name: 'Chile', avatar: '🇨🇱', continent: 'South America', tier: 2, persona: Personas.CHL_PERSONA, profile: 'A long, narrow country...', detailedProfile: 'Chile is known for its dramatic landscapes...', motto: 'Por la Razón o la Fuerza', established: 'September 18, 1810', nationalDay: 'September 18', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['White and non-indigenous', 'Mapuche'] },
    'CHN': { id: 'CHN', name: 'China', avatar: '🇨🇳', continent: 'Asia', tier: 1, persona: Personas.CHN_PERSONA, profile: 'A major economic power with a long history...', detailedProfile: 'China is the world\'s most populous country...', motto: '为人民服务', established: 'October 1, 1949', nationalDay: 'October 1', newYear: 'Lunar New Year', language: 'Standard Chinese (Mandarin)', ethnic_groups: ['Han Chinese', 'Zhuang', 'Manchu', 'Hui', 'Miao'] },
    'COL': { id: 'COL', name: 'Colombia', avatar: '🇨🇴', continent: 'South America', tier: 2, persona: Personas.COL_PERSONA, profile: 'A country at the northern tip of South America...', detailedProfile: 'Colombia is known for its high-quality coffee...', motto: 'Libertad y Orden', established: 'July 20, 1810', nationalDay: 'July 20', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mestizo and White', 'Afro-Colombian'] },
    'COM': { id: 'COM', name: 'Comoros', avatar: '🇰🇲', continent: 'Africa', tier: 3, persona: Personas.COM_PERSONA, profile: 'A volcanic archipelago off Africa’s east coast...', detailedProfile: 'The Comoros is a sovereign island nation...', motto: 'Unité, Solidarité, Développement', established: 'July 6, 1975', nationalDay: 'July 6', newYear: 'January 1', language: 'Comorian, Arabic, French', ethnic_groups: ['Comorian'] },
    'CRI': { id: 'CRI', name: 'Costa Rica', avatar: '🇨🇷', continent: 'North America', tier: 3, persona: Personas.CRI_PERSONA, profile: 'A rugged, rainforested Central American country...', detailedProfile: 'Costa Rica is renowned for its biodiversity...', motto: 'Vivan siempre el trabajo y la paz', established: 'September 15, 1821', nationalDay: 'September 15', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['White or Mestizo', 'Black or Afro-Caribbean'] },
    'HRV': { id: 'HRV', name: 'Croatia', avatar: '🇭🇷', continent: 'Europe', tier: 3, persona: Personas.HRV_PERSONA, profile: 'An Eastern European country with a long coastline...', detailedProfile: 'Croatia joined the European Union in 2013...', motto: 'N/A', established: 'June 25, 1991', nationalDay: 'May 30', newYear: 'January 1', language: 'Croatian', ethnic_groups: ['Croat', 'Serb'] },
    'CUB': { id: 'CUB', name: 'Cuba', avatar: '🇨🇺', continent: 'North America', tier: 3, persona: Personas.CUB_PERSONA, profile: 'A Caribbean island nation under communist rule...', detailedProfile: 'Cuba is known for its classic American cars...', motto: 'Patria o Muerte, Venceremos!', established: 'May 20, 1902', nationalDay: 'January 1', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['White', 'Mulatto and Mestizo', 'Black'] },
    'CYP': { id: 'CYP', name: 'Cyprus', avatar: '🇨🇾', continent: 'Asia', tier: 3, persona: Personas.CYP_PERSONA, profile: 'An island country in the Eastern Mediterranean...', detailedProfile: 'Cyprus has been divided since 1974...', motto: 'Δεν ξεχνώ και αγωνίζομαι', established: 'August 16, 1960', nationalDay: 'October 1', newYear: 'January 1', language: 'Greek, Turkish', ethnic_groups: ['Greek Cypriot', 'Turkish Cypriot'] },
    'CZE': { id: 'CZE', name: 'Czech Republic', avatar: '🇨🇿', continent: 'Europe', tier: 2, persona: Personas.CZE_PERSONA, profile: 'A landlocked country in Central Europe...', detailedProfile: 'The Czech Republic, also known as Czechia...', motto: 'Pravda vítězí', established: 'January 1, 1993', nationalDay: 'October 28', newYear: 'January 1', language: 'Czech', ethnic_groups: ['Czech', 'Moravian', 'Slovak'] },
    'DNK': { id: 'DNK', name: 'Denmark', avatar: '🇩🇰', continent: 'Europe', tier: 2, persona: Personas.DNK_PERSONA, profile: 'A Scandinavian country...', detailedProfile: 'Denmark is a constitutional monarchy...', motto: 'Guds hjælp, Folkets kærlighed, Danmarks styrke', established: 'c. 965', nationalDay: 'June 5', newYear: 'January 1', language: 'Danish', ethnic_groups: ['Danish', 'Greenlandic', 'Faroese'] },
    'DJI': { id: 'DJI', name: 'Djibouti', avatar: '🇩🇯', continent: 'Africa', tier: 3, persona: Personas.DJI_PERSONA, profile: 'A country located in the Horn of Africa...', detailedProfile: 'Djibouti\'s strategic location...', motto: 'Unité, Égalité, Paix', established: 'June 27, 1977', nationalDay: 'June 27', newYear: 'January 1', language: 'French, Arabic', ethnic_groups: ['Issa', 'Afar'] },
    'DOM': { id: 'DOM', name: 'Dominican Republic', avatar: '🇩🇴', continent: 'North America', tier: 3, persona: Personas.DOM_PERSONA, profile: 'A Caribbean nation that shares the island of Hispaniola...', detailedProfile: 'The Dominican Republic has the Caribbean\'s largest economy...', motto: 'Dios, Patria, Libertad', established: 'February 27, 1844', nationalDay: 'February 27', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mixed', 'Black', 'White'] },
    'ECU': { id: 'ECU', name: 'Ecuador', avatar: '🇪🇨', continent: 'South America', tier: 3, persona: Personas.ECU_PERSONA, profile: 'A country straddling the equator...', detailedProfile: 'Ecuador is named for the equator...', motto: 'Dios, patria y libertad', established: 'May 24, 1822', nationalDay: 'August 10', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mestizo', 'Montubio', 'Amerindian', 'White'] },
    'EGY': { id: 'EGY', name: 'Egypt', avatar: '🇪🇬', continent: 'Africa', tier: 2, persona: Personas.EGY_PERSONA, profile: 'A country linking northeast Africa with the Middle East...', detailedProfile: 'Egypt is home to one of the world\'s earliest and greatest civilizations...', motto: 'N/A', established: 'February 28, 1922', nationalDay: 'July 23', newYear: 'January 1', language: 'Arabic', ethnic_groups: ['Egyptian'] },
    'SLV': { id: 'SLV', name: 'El Salvador', avatar: '🇸🇻', continent: 'North America', tier: 3, profile: 'A small Central American nation...', detailedProfile: 'El Salvador is the smallest and most densely populated country...', motto: 'Dios, Unión, Libertad', established: 'September 15, 1821', nationalDay: 'September 15', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mestizo', 'White'] },
    'GNQ': { id: 'GNQ', name: 'Equatorial Guinea', avatar: '🇬🇶', continent: 'Africa', tier: 3, persona: Personas.GNQ_PERSONA, profile: 'A Central African country...', detailedProfile: 'Equatorial Guinea has become one of sub-Saharan Africa\'s biggest oil producers...', motto: 'Unidad, Paz, Justicia', established: 'October 12, 1968', nationalDay: 'October 12', newYear: 'January 1', language: 'Spanish, French, Portuguese', ethnic_groups: ['Fang', 'Bubi'] },
    'EST': { id: 'EST', name: 'Estonia', avatar: '🇪🇪', continent: 'Europe', tier: 3, persona: Personas.EST_PERSONA, profile: 'A country in Northern Europe...', detailedProfile: 'Estonia is a leader in e-government...', motto: 'N/A', established: 'February 24, 1918', nationalDay: 'February 24', newYear: 'January 1', language: 'Estonian', ethnic_groups: ['Estonian', 'Russian'] },
    'SWZ': { id: 'SWZ', name: 'Eswatini', avatar: '🇸🇿', continent: 'Africa', tier: 3, profile: 'A small, landlocked monarchy...', detailedProfile: 'Eswatini is led by King Mswati III...', motto: 'Siyinqaba', established: 'September 6, 1968', nationalDay: 'September 6', newYear: 'January 1', language: 'Swazi, English', ethnic_groups: ['Swazi', 'Zulu'] },
    'ETH': { id: 'ETH', name: 'Ethiopia', avatar: '🇪🇹', continent: 'Africa', tier: 2, persona: Personas.ETH_PERSONA, profile: 'A rugged, landlocked country...', detailedProfile: 'Ethiopia is the cradle of mankind...', motto: 'N/A', established: 'c. 980 BC', nationalDay: 'May 28', newYear: 'Enkutatash (September 11)', language: 'Amharic, Oromo, Somali, Tigrinya', ethnic_groups: ['Oromo', 'Amhara', 'Somali', 'Tigrayan'] },
    'FJI': { id: 'FJI', name: 'Fiji', avatar: '🇫🇯', continent: 'Oceania', tier: 3, persona: Personas.FJI_PERSONA, profile: 'A country in the South Pacific...', detailedProfile: 'Fiji is famed for its rugged landscapes...', motto: 'Rerevaka na Kalou ka Doka na Tui', established: 'October 10, 1970', nationalDay: 'October 10', newYear: 'January 1', language: 'English, Fijian, Hindi', ethnic_groups: ['iTaukei (Indigenous Fijian)', 'Indo-Fijian'] },
    'FIN': { id: 'FIN', name: 'Finland', avatar: '🇫🇮', continent: 'Europe', tier: 2, persona: Personas.FIN_PERSONA, profile: 'A Northern European nation...', detailedProfile: 'Finland is often ranked as the "happiest country in the world."...', motto: 'N/A', established: 'December 6, 1917', nationalDay: 'December 6', newYear: 'January 1', language: 'Finnish, Swedish', ethnic_groups: ['Finnish', 'Swede'] },
    'FRA': { id: 'FRA', name: 'France', avatar: '🇫🇷', continent: 'Europe', tier: 1, persona: Personas.FRA_PERSONA, profile: 'A central Western European nation...', detailedProfile: 'France is a republic renowned for its sophisticated cuisine...', motto: 'Liberté, égalité, fraternité', established: 'September 22, 1792', nationalDay: 'July 14', newYear: 'January 1', language: 'French', ethnic_groups: ['French', 'German', 'Breton', 'Catalan', 'Basque'] },
    'GAB': { id: 'GAB', name: 'Gabon', avatar: '🇬🇦', continent: 'Africa', tier: 3, persona: Personas.GAB_PERSONA, profile: 'A country along the Atlantic coast...', detailedProfile: 'Gabon is one of the most prosperous and stable countries...', motto: 'Union, Travail, Justice', established: 'August 17, 1960', nationalDay: 'August 17', newYear: 'January 1', language: 'French', ethnic_groups: ['Fang', 'Myene', 'Punu-Sira-Nzebi'] },
    'GMB': { id: 'GMB', name: 'Gambia', avatar: '🇬🇲', continent: 'Africa', tier: 3, persona: Personas.GMB_PERSONA, profile: 'A small West African country...', detailedProfile: 'The Gambia is almost entirely surrounded by Senegal...', motto: 'Progress, Peace, Prosperity', established: 'February 18, 1965', nationalDay: 'February 18', newYear: 'January 1', language: 'English', ethnic_groups: ['Mandinka', 'Fula', 'Wolof', 'Jola'] },
    'GEO': { id: 'GEO', name: 'Georgia', avatar: '🇬🇪', continent: 'Asia', tier: 3, persona: Personas.GEO_PERSONA, profile: 'A country at the intersection of Europe and Asia...', detailedProfile: 'Georgia is famous for its winemaking tradition...', motto: 'ძალა ერთობაშია', established: 'December 25, 1991', nationalDay: 'May 26', newYear: 'January 1', language: 'Georgian', ethnic_groups: ['Georgian', 'Azerbaijani', 'Armenian'] },
    'DEU': { id: 'DEU', name: 'Germany', avatar: '🇩🇪', continent: 'Europe', tier: 1, persona: Personas.DEU_PERSONA, profile: 'An economic powerhouse in Europe...', detailedProfile: 'Germany is known for its precision engineering...', motto: 'Einigkeit und Recht und Freiheit', established: 'May 23, 1949', nationalDay: 'October 3', newYear: 'January 1', language: 'German', ethnic_groups: ['German', 'Turkish', 'Polish', 'Syrian'] },
    'GHA': { id: 'GHA', name: 'Ghana', avatar: '🇬🇭', continent: 'Africa', tier: 3, persona: Personas.GHA_PERSONA, profile: 'A country in West Africa...', detailedProfile: 'Ghana was the first sub-Saharan country to gain independence...', motto: 'Freedom and Justice', established: 'March 6, 1957', nationalDay: 'March 6', newYear: 'January 1', language: 'English', ethnic_groups: ['Akan', 'Mole-Dagbon', 'Ewe', 'Ga-Dangme'] },
    'GRC': { id: 'GRC', name: 'Greece', avatar: '🇬🇷', continent: 'Europe', tier: 2, persona: Personas.GRC_PERSONA, profile: 'A country in southeastern Europe...', detailedProfile: 'Greece is known as the birthplace of democracy...', motto: 'Ελευθερία ή Θάνατος', established: 'March 25, 1821', nationalDay: 'March 25', newYear: 'January 1', language: 'Greek', ethnic_groups: ['Greek'] },
    'GTM': { id: 'GTM', name: 'Guatemala', avatar: '🇬🇹', continent: 'North America', tier: 3, persona: Personas.GTM_PERSONA, profile: 'A Central American country south of Mexico...', detailedProfile: 'Guatemala has a large indigenous population...', motto: 'Libre Crezca Fecundo', established: 'September 15, 1821', nationalDay: 'September 15', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mestizo (Ladino)', 'Maya'] },
    'GIN': { id: 'GIN', name: 'Guinea', avatar: '🇬🇳', continent: 'Africa', tier: 3, persona: Personas.GIN_PERSONA, profile: 'A country in West Africa...', detailedProfile: 'Guinea has the world\'s largest reserves of bauxite...', motto: 'Travail, Justice, Solidarité', established: 'October 2, 1958', nationalDay: 'October 2', newYear: 'January 1', language: 'French', ethnic_groups: ['Fula', 'Mandinka', 'Susu'] },
    'GUY': { id: 'GUY', name: 'Guyana', avatar: '🇬🇾', continent: 'South America', tier: 3, persona: Personas.GUY_PERSONA, profile: 'A country on South America’s North Atlantic coast...', detailedProfile: 'Guyana is the only English-speaking country in South America...', motto: 'One People, One Nation, One Destiny', established: 'May 26, 1966', nationalDay: 'February 23', newYear: 'January 1', language: 'English', ethnic_groups: ['Indo-Guyanese', 'Afro-Guyanese', 'Mixed'] },
    'HTI': { id: 'HTI', name: 'Haiti', avatar: '🇭🇹', continent: 'North America', tier: 3, persona: Personas.HTI_PERSONA, profile: 'A Caribbean country...', detailedProfile: 'Haiti gained independence from France in 1804...', motto: 'L\'union fait la force', established: 'January 1, 1804', nationalDay: 'January 1', newYear: 'January 1', language: 'French, Haitian Creole', ethnic_groups: ['African descent'] },
    'HND': { id: 'HND', name: 'Honduras', avatar: '🇭🇳', continent: 'North America', tier: 3, persona: Personas.HND_PERSONA, profile: 'A Central American country...', detailedProfile: 'Honduras is known for its Mayan ruins...', motto: 'Libre, Soberana e Independiente', established: 'September 15, 1821', nationalDay: 'September 15', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mestizo', 'Indigenous'] },
    'HUN': { id: 'HUN', name: 'Hungary', avatar: '🇭🇺', continent: 'Europe', tier: 2, persona: Personas.HUN_PERSONA, profile: 'A landlocked country in Central Europe...', detailedProfile: 'Hungary has a rich history...', motto: 'N/A', established: '1000 AD', nationalDay: 'August 20', newYear: 'January 1', language: 'Hungarian', ethnic_groups: ['Hungarian', 'Romani'] },
    'ISL': { id: 'ISL', name: 'Iceland', avatar: '🇮🇸', continent: 'Europe', tier: 3, persona: Personas.ISL_PERSONA, profile: 'A Nordic island nation...', detailedProfile: 'Iceland is one of the most sparsely populated countries...', motto: 'N/A', established: 'June 17, 1944', nationalDay: 'June 17', newYear: 'January 1', language: 'Icelandic', ethnic_groups: ['Icelandic'] },
    'IND': { id: 'IND', name: 'India', avatar: '🇮🇳', continent: 'Asia', tier: 1, persona: Personas.IND_PERSONA, profile: 'The world\'s largest democracy...', detailedProfile: 'India is a country of incredible diversity...', motto: 'Satyameva Jayate', established: 'August 15, 1947', nationalDay: 'January 26', newYear: 'Varies (regional)', language: 'Hindi, English', ethnic_groups: ['Indo-Aryan', 'Dravidian'] },
    'IDN': { id: 'IDN', name: 'Indonesia', avatar: '🇮🇩', continent: 'Asia', tier: 2, persona: Personas.IDN_PERSONA, profile: 'A Southeast Asian nation made up of thousands of volcanic islands...', detailedProfile: 'Indonesia is the world\'s fourth most populous country...', motto: 'Bhinneka Tunggal Ika', established: 'August 17, 1945', nationalDay: 'August 17', newYear: 'January 1', language: 'Indonesian', ethnic_groups: ['Javanese', 'Sundanese', 'Malay', 'Batak'] },
    'IRN': { id: 'IRN', name: 'Iran', avatar: '🇮🇷', continent: 'Asia', tier: 2, persona: Personas.IRN_PERSONA, profile: 'An Islamic republic on the Persian Gulf...', detailedProfile: 'Iran, also known as Persia...', motto: 'Esteqlāl, āzādī, jomhūrī-ye eslāmī', established: 'April 1, 1979', nationalDay: 'February 11', newYear: 'Nowruz (March 20/21)', language: 'Persian (Farsi)', ethnic_groups: ['Persian', 'Azerbaijani', 'Kurd', 'Lur'] },
    'IRQ': { id: 'IRQ', name: 'Iraq', avatar: '🇮🇶', continent: 'Asia', tier: 3, persona: Personas.IRQ_PERSONA, profile: 'A country in the Middle East...', detailedProfile: 'Iraq, the site of ancient Mesopotamia...', motto: 'الله أكبر', established: 'October 3, 1932', nationalDay: 'October 3', newYear: 'January 1', language: 'Arabic, Kurdish', ethnic_groups: ['Arab', 'Kurdish', 'Turkmen'] },
    'IRL': { id: 'IRL', name: 'Ireland', avatar: '🇮🇪', continent: 'Europe', tier: 2, persona: Personas.IRL_PERSONA, profile: 'An island in the North Atlantic...', detailedProfile: 'The Republic of Ireland has a modern, knowledge-based economy...', motto: 'N/A', established: 'December 6, 1922', nationalDay: 'March 17 (St. Patrick\'s Day)', newYear: 'January 1', language: 'Irish, English', ethnic_groups: ['Irish', 'White', 'Asian', 'Black'] },
    'ISR': { id: 'ISR', name: 'Israel', avatar: '🇮🇱', continent: 'Asia', tier: 2, persona: Personas.ISR_PERSONA, profile: 'A Middle Eastern country on the Mediterranean Sea...', detailedProfile: 'Israel is a parliamentary democracy...', motto: 'N/A', established: 'May 14, 1948', nationalDay: 'Varies (Iyar 5)', newYear: 'Rosh Hashanah (Varies)', language: 'Hebrew, Arabic', ethnic_groups: ['Jewish', 'Arab'] },
    'ITA': { id: 'ITA', name: 'Italy', avatar: '🇮🇹', continent: 'Europe', tier: 1, persona: Personas.ITA_PERSONA, profile: 'A European country with a long Mediterranean coastline...', detailedProfile: 'Italy is home to the greatest number of UNESCO World Heritage Sites...', motto: 'N/A', established: 'June 2, 1946', nationalDay: 'June 2', newYear: 'January 1', language: 'Italian', ethnic_groups: ['Italian'] },
    'JAM': { id: 'JAM', name: 'Jamaica', avatar: '🇯🇲', continent: 'North America', tier: 3, persona: Personas.JAM_PERSONA, profile: 'A Caribbean island nation...', detailedProfile: 'Jamaica is the birthplace of reggae music...', motto: 'Out of Many, One People', established: 'August 6, 1962', nationalDay: 'August 6', newYear: 'January 1', language: 'English', ethnic_groups: ['African descent', 'Mixed'] },
    'JPN': { id: 'JPN', name: 'Japan', avatar: '🇯🇵', continent: 'Asia', tier: 1, persona: Personas.JPN_PERSONA, profile: 'An island nation where ancient tradition meets futuristic technology...', detailedProfile: 'Japan is an archipelago in East Asia...', motto: 'N/A', established: 'February 11, 660 BC (Traditional)', nationalDay: 'February 11', newYear: 'January 1', language: 'Japanese', ethnic_groups: ['Japanese'] },
    'JOR': { id: 'JOR', name: 'Jordan', avatar: '🇯🇴', continent: 'Asia', tier: 3, persona: Personas.JOR_PERSONA, profile: 'An Arab nation on the east bank of the Jordan River...', detailedProfile: 'Jordan is considered a safe haven...', motto: 'الله، الوطن، الملك', established: 'May 25, 1946', nationalDay: 'May 25', newYear: 'January 1', language: 'Arabic', ethnic_groups: ['Arab (including many of Palestinian origin)'] },
    'KAZ': { id: 'KAZ', name: 'Kazakhstan', avatar: '🇰🇿', continent: 'Asia', tier: 2, persona: Personas.KAZ_PERSONA, profile: 'A vast Central Asian country...', detailedProfile: 'Kazakhstan is the world\'s largest landlocked country...', motto: 'N/A', established: 'December 16, 1991', nationalDay: 'October 25', newYear: 'January 1', language: 'Kazakh, Russian', ethnic_groups: ['Kazakh', 'Russian', 'Uzbek'] },
    'KEN': { id: 'KEN', name: 'Kenya', avatar: '🇰🇪', continent: 'Africa', tier: 2, persona: Personas.KEN_PERSONA, profile: 'A country in East Africa...', detailedProfile: 'Kenya is famous for its wildlife safaris...', motto: 'Harambee', established: 'December 12, 1963', nationalDay: 'December 12', newYear: 'January 1', language: 'Swahili, English', ethnic_groups: ['Kikuyu', 'Luhya', 'Kalenjin', 'Luo', 'Kamba'] },
    'KWT': { id: 'KWT', name: 'Kuwait', avatar: '🇰🇼', continent: 'Asia', tier: 3, persona: Personas.KWT_PERSONA, profile: 'An Arab country on the Persian (Arabian) Gulf...', detailedProfile: 'Kuwait has the world\'s sixth largest oil reserves...', motto: 'N/A', established: 'June 19, 1961', nationalDay: 'February 25', newYear: 'January 1', language: 'Arabic', ethnic_groups: ['Kuwaiti', 'other Arab', 'Asian'] },
    'KGZ': { id: 'KGZ', name: 'Kyrgyzstan', avatar: '🇰🇬', continent: 'Asia', tier: 3, persona: Personas.KGZ_PERSONA, profile: 'A rugged Central Asian country...', detailedProfile: 'Kyrgyzstan is known for its stunning natural beauty...', motto: 'N/A', established: 'August 31, 1991', nationalDay: 'August 31', newYear: 'Nowruz (March 21)', language: 'Kyrgyz, Russian', ethnic_groups: ['Kyrgyz', 'Uzbek', 'Russian'] },
    'LAO': { id: 'LAO', name: 'Laos', avatar: '🇱🇦', continent: 'Asia', tier: 3, profile: 'A Southeast Asian country traversed by the Mekong River...', detailedProfile: 'Laos is a landlocked, mountainous country...', motto: 'Peace, Independence, Democracy, Unity and Prosperity', established: 'July 19, 1949', nationalDay: 'December 2', newYear: 'Pi Mai (April 14-16)', language: 'Lao', ethnic_groups: ['Lao', 'Khmu', 'Hmong'] },
    'LVA': { id: 'LVA', name: 'Latvia', avatar: '🇱🇻', continent: 'Europe', tier: 3, profile: 'A country on the Baltic Sea...', detailedProfile: 'Latvia is a member of the EU, NATO...', motto: 'Tēvzemei un Brīvībai', established: 'November 18, 1918', nationalDay: 'November 18', newYear: 'January 1', language: 'Latvian', ethnic_groups: ['Latvian', 'Russian'] },
    'LBN': { id: 'LBN', name: 'Lebanon', avatar: '🇱🇧', continent: 'Asia', tier: 3, profile: 'A Middle Eastern country...', detailedProfile: 'Lebanon was once known as the "Switzerland of the Middle East"...', motto: 'كلنا للوطن، للعلا، للعلم', established: 'November 22, 1943', nationalDay: 'November 22', newYear: 'January 1', language: 'Arabic, French', ethnic_groups: ['Arab (includes many Christian sects)'] },
    'LSO': { id: 'LSO', name: 'Lesotho', avatar: '🇱🇸', continent: 'Africa', tier: 3, profile: 'A high-altitude, landlocked kingdom...', detailedProfile: 'Lesotho is an enclave, entirely surrounded by South Africa...', motto: 'Khotso, Pula, Nala', established: 'October 4, 1966', nationalDay: 'October 4', newYear: 'January 1', language: 'Sesotho, English', ethnic_groups: ['Sotho'] },
    'LBR': { id: 'LBR', name: 'Liberia', avatar: '🇱🇷', continent: 'Africa', tier: 3, profile: 'A country on the West African coast...', detailedProfile: 'Liberia was founded by freed American slaves...', motto: 'The love of liberty brought us here', established: 'July 26, 1847', nationalDay: 'July 26', newYear: 'January 1', language: 'English', ethnic_groups: ['Kpelle', 'Bassa', 'Grebo', 'Gio'] },
    'LBY': { id: 'LBY', name: 'Libya', avatar: '🇱🇾', continent: 'Africa', tier: 3, profile: 'A country in the Maghreb region...', detailedProfile: 'Libya has the largest oil reserves in Africa...', motto: 'N/A', established: 'December 24, 1951', nationalDay: 'February 17', newYear: 'January 1', language: 'Arabic', ethnic_groups: ['Arab-Berber'] },
    'LIE': { id: 'LIE', name: 'Liechtenstein', avatar: '🇱🇮', continent: 'Europe', tier: 3, profile: 'A German-speaking, 25km-long principality...', detailedProfile: 'Liechtenstein is a microstate between Austria and Switzerland...', motto: 'Für Gott, Fürst und Vaterland', established: 'January 23, 1719', nationalDay: 'August 15', newYear: 'January 1', language: 'German', ethnic_groups: ['Liechtensteiner', 'Swiss', 'Austrian'] },
    'LTU': { id: 'LTU', name: 'Lithuania', avatar: '🇱🇹', continent: 'Europe', tier: 3, profile: 'A country in the Baltic region...', detailedProfile: 'Lithuania was the first Soviet republic to declare independence...', motto: 'Tautos jėga vienybėje', established: 'February 16, 1918', nationalDay: 'February 16', newYear: 'January 1', language: 'Lithuanian', ethnic_groups: ['Lithuanian', 'Polish', 'Russian'] },
    'LUX': { id: 'LUX', name: 'Luxembourg', avatar: '🇱🇺', continent: 'Europe', tier: 3, profile: 'A small European country...', detailedProfile: 'Luxembourg is one of the world\'s wealthiest countries...', motto: 'Mir wëlle bleiwe wat mir sinn', established: 'April 19, 1839', nationalDay: 'June 23', newYear: 'January 1', language: 'Luxembourgish, French, German', ethnic_groups: ['Luxembourger', 'Portuguese', 'French', 'Italian'] },
    'MDG': { id: 'MDG', name: 'Madagascar', avatar: '🇲🇬', continent: 'Africa', tier: 3, profile: 'A huge island nation off the southeast coast of Africa...', detailedProfile: 'Madagascar is home to thousands of animal species found nowhere else...', motto: 'Fitiavana, Tanindrazana, Fandrosoana', established: 'June 26, 1960', nationalDay: 'June 26', newYear: 'January 1', language: 'Malagasy, French', ethnic_groups: ['Malayo-Indonesian', 'Cotiers'] },
    'MWI': { id: 'MWI', name: 'Malawi', avatar: '🇲🇼', continent: 'Africa', tier: 3, profile: 'A landlocked country in southeastern Africa...', detailedProfile: 'Malawi is nicknamed the "Warm Heart of Africa"...', motto: 'Unity and Freedom', established: 'July 6, 1964', nationalDay: 'July 6', newYear: 'January 1', language: 'English, Chewa', ethnic_groups: ['Chewa', 'Lomwe', 'Yao', 'Ngoni'] },
    'MYS': { id: 'MYS', name: 'Malaysia', avatar: '🇲🇾', continent: 'Asia', tier: 2, profile: 'A Southeast Asian country...', detailedProfile: 'Malaysia is a federal constitutional monarchy...', motto: 'Bersekutu Bertambah Mutu', established: 'August 31, 1957', nationalDay: 'August 31', newYear: 'January 1', language: 'Malay', ethnic_groups: ['Malay', 'Chinese', 'Indian'] },
    'MDV': { id: 'MDV', name: 'Maldives', avatar: '🇲🇻', continent: 'Asia', tier: 3, profile: 'A tropical nation in the Indian Ocean...', detailedProfile: 'The Maldives is a chain of nearly 1,200 islands...', motto: 'N/A', established: 'July 26, 1965', nationalDay: 'July 26', newYear: 'January 1', language: 'Dhivehi', ethnic_groups: ['Maldivian'] },
    'MLI': { id: 'MLI', name: 'Mali', avatar: '🇲🇱', continent: 'Africa', tier: 3, profile: 'A landlocked country in West Africa...', detailedProfile: 'Mali was once part of three powerful West African empires...', motto: 'Un peuple, un but, une foi', established: 'September 22, 1960', nationalDay: 'September 22', newYear: 'January 1', language: 'French', ethnic_groups: ['Bambara', 'Fula', 'Senufo'] },
    'MLT': { id: 'MLT', name: 'Malta', avatar: '🇲🇹', continent: 'Europe', tier: 3, profile: 'An archipelago in the central Mediterranean...', detailedProfile: 'Malta is a member of the EU...', motto: 'Virtute et Constantia', established: 'September 21, 1964', nationalDay: 'September 21', newYear: 'January 1', language: 'Maltese, English', ethnic_groups: ['Maltese'] },
    'MRT': { id: 'MRT', name: 'Mauritania', avatar: '🇲🇷', continent: 'Africa', tier: 3, profile: 'A country in Northwest Africa...', detailedProfile: 'Mauritania is almost entirely desert...', motto: 'شرف، إخاء، عدل', established: 'November 28, 1960', nationalDay: 'November 28', newYear: 'January 1', language: 'Arabic', ethnic_groups: ['Black Moors (Haratin)', 'White Moors (Bidan)', 'Sub-Saharan Africans'] },
    'MUS': { id: 'MUS', name: 'Mauritius', avatar: '🇲🇺', continent: 'Africa', tier: 3, profile: 'An Indian Ocean island nation...', detailedProfile: 'Mauritius is known for its beaches, lagoons and reefs...', motto: 'Stella Clavisque Maris Indici', established: 'March 12, 1968', nationalDay: 'March 12', newYear: 'January 1', language: 'English, French', ethnic_groups: ['Indo-Mauritian', 'Creole', 'Sino-Mauritian', 'Franco-Mauritian'] },
    'MEX': { id: 'MEX', name: 'Mexico', avatar: '🇲🇽', continent: 'North America', tier: 2, profile: 'A country in the southern portion of North America...', detailedProfile: 'Mexico is home to ancient ruins...', motto: 'N/A', established: 'September 16, 1810', nationalDay: 'September 16', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mestizo', 'Indigenous'] },
    'MDA': { id: 'MDA', name: 'Moldova', avatar: '🇲🇩', continent: 'Europe', tier: 3, profile: 'An Eastern European country...', detailedProfile: 'Moldova is a landlocked country known for its wine regions...', motto: 'N/A', established: 'August 27, 1991', nationalDay: 'August 27', newYear: 'January 1', language: 'Romanian (Moldovan)', ethnic_groups: ['Moldovan', 'Romanian', 'Ukrainian', 'Gagauz', 'Russian'] },
    'MCO': { id: 'MCO', name: 'Monaco', avatar: '🇲🇨', continent: 'Europe', tier: 3, profile: 'An independent city-state...', detailedProfile: 'Monaco is the second-smallest sovereign state...', motto: 'Deo Juvante', established: '1297', nationalDay: 'November 19', newYear: 'January 1', language: 'French', ethnic_groups: ['French', 'Monégasque', 'Italian'] },
    'MNG': { id: 'MNG', name: 'Mongolia', avatar: '🇲🇳', continent: 'Asia', tier: 3, profile: 'A nation bordered by China and Russia...', detailedProfile: 'Mongolia is known as the "Land of the Blue Sky"...', motto: 'N/A', established: 'December 29, 1911', nationalDay: 'July 11', newYear: 'Tsagaan Sar (Lunar New Year)', language: 'Mongolian', ethnic_groups: ['Khalkh', 'Kazakh'] },
    'MNE': { id: 'MNE', name: 'Montenegro', avatar: '🇲🇪', continent: 'Europe', tier: 3, profile: 'A Balkan country with rugged mountains...', detailedProfile: 'Montenegro is a popular tourist destination...', motto: 'N/A', established: 'June 3, 2006', nationalDay: 'July 13', newYear: 'January 1', language: 'Montenegrin', ethnic_groups: ['Montenegrin', 'Serb', 'Bosniak'] },
    'MAR': { id: 'MAR', name: 'Morocco', avatar: '🇲🇦', continent: 'Africa', tier: 2, profile: 'A North African country...', detailedProfile: 'Morocco is a constitutional monarchy...', motto: 'الله، الوطن، الملك', established: 'April 7, 1956', nationalDay: 'July 30', newYear: 'January 1', language: 'Arabic, Tamazight', ethnic_groups: ['Arab-Berber'] },
    'MOZ': { id: 'MOZ', name: 'Mozambique', avatar: '🇲🇿', continent: 'Africa', tier: 3, profile: 'A southern African nation...', detailedProfile: 'Mozambique has some of the world\'s largest untapped natural gas reserves...', motto: 'N/A', established: 'June 25, 1975', nationalDay: 'June 25', newYear: 'January 1', language: 'Portuguese', ethnic_groups: ['Makhuwa', 'Tsonga', 'Shona'] },
    'MMR': { id: 'MMR', name: 'Myanmar', avatar: '🇲🇲', continent: 'Asia', tier: 3, profile: 'A Southeast Asian nation...', detailedProfile: 'Myanmar, formerly Burma...', motto: 'N/A', established: 'January 4, 1948', nationalDay: 'January 4', newYear: 'Thingyan (April 13-16)', language: 'Burmese', ethnic_groups: ['Bamar', 'Shan', 'Karen'] },
    'NAM': { id: 'NAM', name: 'Namibia', avatar: '🇳🇦', continent: 'Africa', tier: 3, profile: 'A country in southwest Africa...', detailedProfile: 'Namibia is one of the least densely populated countries...', motto: 'Unity, Liberty, Justice', established: 'March 21, 1990', nationalDay: 'March 21', newYear: 'January 1', language: 'English', ethnic_groups: ['Ovambo', 'Kavango', 'Herero', 'Damara'] },
    'NPL': { id: 'NPL', name: 'Nepal', avatar: '🇳🇵', continent: 'Asia', tier: 3, profile: 'A landlocked country in South Asia...', detailedProfile: 'Nepal is home to eight of the world\'s ten tallest mountains...', motto: 'जननी जन्मभूमिश्च स्वर्गादपि गरीयसी', established: 'May 28, 2008', nationalDay: 'September 20', newYear: 'Bikram Samwat (mid-April)', language: 'Nepali', ethnic_groups: ['Chhetri', 'Brahman-Hill', 'Magar', 'Tharu'] },
    'NLD': { id: 'NLD', name: 'Netherlands', avatar: '🇳🇱', continent: 'Europe', tier: 2, profile: 'A country in northwestern Europe...', detailedProfile: 'The Netherlands is a densely populated country...', motto: 'Je maintiendrai', established: '1581', nationalDay: 'April 27', newYear: 'January 1', language: 'Dutch', ethnic_groups: ['Dutch', 'Frisian'] },
    'NZL': { id: 'NZL', name: 'New Zealand', avatar: '🇳🇿', continent: 'Oceania', tier: 2, profile: 'An island country in the southwestern Pacific Ocean...', detailedProfile: 'New Zealand is famous for its dramatic scenery...', motto: 'N/A (formerly "Onward")', established: 'September 26, 1907', nationalDay: 'February 6', newYear: 'January 1', language: 'English, Māori', ethnic_groups: ['European', 'Māori', 'Asian', 'Pacific peoples'] },
    'NIC': { id: 'NIC', name: 'Nicaragua', avatar: '🇳🇮', continent: 'North America', tier: 3, profile: 'A country in Central America...', detailedProfile: 'Nicaragua is the largest country in Central America...', motto: 'En Dios Confiamos', established: 'September 15, 1821', nationalDay: 'September 15', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mestizo', 'White'] },
    'NER': { id: 'NER', name: 'Niger', avatar: '🇳🇪', continent: 'Africa', tier: 3, profile: 'A landlocked country in West Africa...', detailedProfile: 'Over 80% of Niger\'s land area lies in the Sahara Desert...', motto: 'Fraternité, Travail, Progrès', established: 'August 3, 1960', nationalDay: 'December 18', newYear: 'January 1', language: 'French', ethnic_groups: ['Hausa', 'Zarma-Songhai', 'Tuareg'] },
    'NGA': { id: 'NGA', name: 'Nigeria', avatar: '🇳🇬', continent: 'Africa', tier: 2, profile: 'A country on the Gulf of Guinea...', detailedProfile: 'Nigeria is a diverse country with over 250 ethnic groups...', motto: 'Unity and Faith, Peace and Progress', established: 'October 1, 1960', nationalDay: 'October 1', newYear: 'January 1', language: 'English', ethnic_groups: ['Hausa', 'Yoruba', 'Igbo'] },
    'PRK': { id: 'PRK', name: 'North Korea', avatar: '🇰🇵', continent: 'Asia', tier: 3, profile: 'Officially the Democratic People\'s Republic of Korea...', detailedProfile: 'North Korea is one of the most secretive and totalitarian countries...', motto: '강성대국', established: 'September 9, 1948', nationalDay: 'September 9', newYear: 'Lunar New Year', language: 'Korean', ethnic_groups: ['Korean'] },
    'MKD': { id: 'MKD', name: 'North Macedonia', avatar: '🇲🇰', continent: 'Europe', tier: 3, profile: 'A country in the Balkan Peninsula...', detailedProfile: 'North Macedonia changed its name in 2019...', motto: 'Слобода или смрт', established: 'September 8, 1991', nationalDay: 'September 8', newYear: 'January 1', language: 'Macedonian', ethnic_groups: ['Macedonian', 'Albanian'] },
    'NOR': { id: 'NOR', name: 'Norway', avatar: '🇳🇴', continent: 'Europe', tier: 2, profile: 'A Scandinavian country...', detailedProfile: 'Norway has one of the highest standards of living...', motto: 'Alt for Norge', established: 'June 7, 1905', nationalDay: 'May 17', newYear: 'January 1', language: 'Norwegian', ethnic_groups: ['Norwegian', 'Sami'] },
    'OMN': { id: 'OMN', name: 'Oman', avatar: '🇴🇲', continent: 'Asia', tier: 3, profile: 'A nation on the Arabian Peninsula...', detailedProfile: 'Oman has a rich maritime history...', motto: 'N/A', established: '1970 (Modern)', nationalDay: 'November 18', newYear: 'January 1', language: 'Arabic', ethnic_groups: ['Arab', 'Baluchi', 'South Asian'] },
    'PAK': { id: 'PAK', name: 'Pakistan', avatar: '🇵🇰', continent: 'Asia', tier: 2, profile: 'A country in South Asia...', detailedProfile: 'Pakistan has a diverse landscape...', motto: 'Īmān, Ittiḥād, Naẓm', established: 'August 14, 1947', nationalDay: 'March 23', newYear: 'January 1', language: 'Urdu, English', ethnic_groups: ['Punjabi', 'Pashtun', 'Sindhi', 'Saraiki', 'Muhajir', 'Baloch'] },
    'PAN': { id: 'PAN', name: 'Panama', avatar: '🇵🇦', continent: 'North America', tier: 3, profile: 'A country on the isthmus linking Central and South America...', detailedProfile: 'The Panama Canal is a key conduit for international maritime trade...', motto: 'Pro Mundi Beneficio', established: 'November 3, 1903', nationalDay: 'November 3', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mestizo', 'Black', 'Amerindian'] },
    'PNG': { id: 'PNG', name: 'Papua New Guinea', avatar: '🇵🇬', continent: 'Oceania', tier: 3, profile: 'An island country in the southwestern Pacific...', detailedProfile: 'Papua New Guinea is home to hundreds of distinct indigenous groups...', motto: 'Unity in Diversity', established: 'September 16, 1975', nationalDay: 'September 16', newYear: 'January 1', language: 'English, Tok Pisin, Hiri Motu', ethnic_groups: ['Melanesian, Papuan, Negrito, Micronesian, Polynesian'] },
    'PRY': { id: 'PRY', name: 'Paraguay', avatar: '🇵🇾', continent: 'South America', tier: 3, profile: 'A landlocked country...', detailedProfile: 'Paraguay is a major producer of soybeans and beef...', motto: 'Paz y justicia', established: 'May 14, 1811', nationalDay: 'May 14', newYear: 'January 1', language: 'Spanish, Guarani', ethnic_groups: ['Mestizo'] },
    'PER': { id: 'PER', name: 'Peru', avatar: '🇵🇪', continent: 'South America', tier: 2, profile: 'A country in South America that\'s home to a section of Amazon rainforest...', detailedProfile: 'Peru is known for its rich history, particularly the Inca civilization...', motto: 'Firme y feliz por la unión', established: 'July 28, 1821', nationalDay: 'July 28', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mestizo', 'Amerindian', 'White', 'Afro-Peruvian'] },
    'PHL': { id: 'PHL', name: 'Philippines', avatar: '🇵🇭', continent: 'Asia', tier: 2, profile: 'A Southeast Asian country in the Western Pacific...', detailedProfile: 'The Philippines has a rich culture...', motto: 'Maka-Diyos, Maka-tao, Makakalikasan at Makabansa', established: 'June 12, 1898', nationalDay: 'June 12', newYear: 'January 1', language: 'Filipino, English', ethnic_groups: ['Tagalog', 'Bisaya/Binisaya', 'Cebuano', 'Ilocano'] },
    'POL': { id: 'POL', name: 'Poland', avatar: '🇵🇱', continent: 'Europe', tier: 2, profile: 'An eastern European country on the Baltic Sea...', detailedProfile: 'Poland has a long history of resilience...', motto: 'N/A', established: 'November 11, 1918', nationalDay: 'November 11', newYear: 'January 1', language: 'Polish', ethnic_groups: ['Polish'] },
    'PRT': { id: 'PRT', name: 'Portugal', avatar: '🇵🇹', continent: 'Europe', tier: 2, profile: 'A southern European country on the Iberian Peninsula...', detailedProfile: 'Portugal is known for its maritime history...', motto: 'N/A', established: 'October 5, 1910', nationalDay: 'June 10', newYear: 'January 1', language: 'Portuguese', ethnic_groups: ['Portuguese'] },
    'QAT': { id: 'QAT', name: 'Qatar', avatar: '🇶🇦', continent: 'Asia', tier: 2, profile: 'A peninsular Arab country...', detailedProfile: 'Qatar is one of the wealthiest countries in the world...', motto: 'N/A', established: 'September 3, 1971', nationalDay: 'December 18', newYear: 'January 1', language: 'Arabic', ethnic_groups: ['non-Qatari', 'Qatari'] },
    'ROU': { id: 'ROU', name: 'Romania', avatar: '🇷🇴', continent: 'Europe', tier: 2, profile: 'A southeastern European country...', detailedProfile: 'Romania is known for the forested region of Transylvania...', motto: 'N/A', established: 'May 9, 1877', nationalDay: 'December 1', newYear: 'January 1', language: 'Romanian', ethnic_groups: ['Romanian', 'Hungarian', 'Roma'] },
    'RUS': { id: 'RUS', name: 'Russia', avatar: '🇷🇺', continent: 'Europe', tier: 1, persona: Personas.RUS_PERSONA, profile: 'The world\'s largest nation...', detailedProfile: 'Russia spans Eastern Europe and Northern Asia...', motto: 'N/A', established: 'December 25, 1991', nationalDay: 'June 12', newYear: 'January 1', language: 'Russian', ethnic_groups: ['Russian', 'Tatar', 'Ukrainian', 'Bashkir'] },
    'RWA': { id: 'RWA', name: 'Rwanda', avatar: '🇷🇼', continent: 'Africa', tier: 3, profile: 'A landlocked country in the Great Rift Valley...', detailedProfile: 'Rwanda is known as the "Land of a Thousand Hills"...', motto: 'Ubumwe, Umurimo, Gukunda Igihugu', established: 'July 1, 1962', nationalDay: 'July 4', newYear: 'January 1', language: 'Kinyarwanda, French, English', ethnic_groups: ['Hutu', 'Tutsi', 'Twa'] },
    'SAU': { id: 'SAU', name: 'Saudi Arabia', avatar: '🇸🇦', continent: 'Asia', tier: 2, profile: 'A desert country encompassing most of the Arabian Peninsula...', detailedProfile: 'Saudi Arabia is the world\'s largest oil exporter...', motto: 'لا إله إلا الله، محمد رسول الله', established: 'September 23, 1932', nationalDay: 'September 23', newYear: 'Based on Hijri calendar', language: 'Arabic', ethnic_groups: ['Arab'] },
    'SEN': { id: 'SEN', name: 'Senegal', avatar: '🇸🇳', continent: 'Africa', tier: 3, profile: 'A country on West Africa’s coast...', detailedProfile: 'Senegal is known for its tradition of "Teranga" or hospitality...', motto: 'Un Peuple, Un But, Une Foi', established: 'April 4, 1960', nationalDay: 'April 4', newYear: 'January 1', language: 'French', ethnic_groups: ['Wolof', 'Fula', 'Serer'] },
    'SRB': { id: 'SRB', name: 'Serbia', avatar: '🇷🇸', continent: 'Europe', tier: 3, profile: 'A landlocked country situated at the crossroads of Central and Southeast Europe...', detailedProfile: 'Serbia has a rich history and culture...', motto: 'Само слога Србина спасава', established: '2006 (Modern)', nationalDay: 'February 15', newYear: 'January 1', language: 'Serbian', ethnic_groups: ['Serb', 'Hungarian'] },
    'SGP': { id: 'SGP', name: 'Singapore', avatar: '🇸🇬', continent: 'Asia', tier: 2, profile: 'An island city-state off southern Malaysia...', detailedProfile: 'Singapore is a global financial center...', motto: 'Majulah Singapura', established: 'August 9, 1965', nationalDay: 'August 9', newYear: 'Lunar New Year', language: 'English, Mandarin, Malay, Tamil', ethnic_groups: ['Chinese', 'Malay', 'Indian'] },
    'SVK': { id: 'SVK', name: 'Slovakia', avatar: '🇸🇰', continent: 'Europe', tier: 3, profile: 'A central European country known for its dramatic natural landscape and many castles...', detailedProfile: 'Slovakia is a member of the EU, NATO...', motto: 'N/A', established: 'January 1, 1993', nationalDay: 'September 1', newYear: 'January 1', language: 'Slovak', ethnic_groups: ['Slovak', 'Hungarian'] },
    'SVN': { id: 'SVN', name: 'Slovenia', avatar: '🇸🇮', continent: 'Europe', tier: 3, profile: 'A country in Central Europe known for its mountains, ski resorts and lakes...', detailedProfile: 'Slovenia was the first former Yugoslav republic to join the EU...', motto: 'N/A', established: 'June 25, 1991', nationalDay: 'June 25', newYear: 'January 1', language: 'Slovene', ethnic_groups: ['Slovene', 'Serb', 'Croat'] },
    'ZAF': { id: 'ZAF', name: 'South Africa', avatar: '🇿🇦', continent: 'Africa', tier: 2, profile: 'A country on the southernmost tip of the African continent...', detailedProfile: 'South Africa is known as the "Rainbow Nation"...', motto: '!ke e: ǀxarra ǁke', established: 'May 31, 1910', nationalDay: 'April 27', newYear: 'January 1', language: 'Zulu, Xhosa, Afrikaans, English, etc. (11 total)', ethnic_groups: ['Black African', 'Coloured', 'White', 'Indian/Asian'] },
    'KOR': { id: 'KOR', name: 'South Korea', avatar: '🇰🇷', continent: 'Asia', tier: 1, persona: Personas.KOR_PERSONA, profile: 'An East Asian nation on the southern half of the Korean Peninsula...', detailedProfile: 'South Korea is known for its tech industry...', motto: '널리 인간 세계를 이롭게 하라', established: 'August 15, 1948', nationalDay: 'August 15', newYear: 'Lunar New Year', language: 'Korean', ethnic_groups: ['Korean'] },
    'ESP': { id: 'ESP', name: 'Spain', avatar: '🇪🇸', continent: 'Europe', tier: 2, profile: 'A country on Europe’s Iberian Peninsula...', detailedProfile: 'Spain is known for its vibrant culture...', motto: 'Plus Ultra', established: '1492 (Unification)', nationalDay: 'October 12', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Spanish (Castilian, Catalan, Galician, Basque)'] },
    'LKA': { id: 'LKA', name: 'Sri Lanka', avatar: '🇱🇰', continent: 'Asia', tier: 3, profile: 'An island country in South Asia...', detailedProfile: 'Sri Lanka is known for its ancient Buddhist ruins...', motto: 'N/A', established: 'February 4, 1948', nationalDay: 'February 4', newYear: 'Sinhala and Tamil New Year (April)', language: 'Sinhala, Tamil', ethnic_groups: ['Sinhalese', 'Sri Lankan Tamil', 'Sri Lankan Moor'] },
    'SWE': { id: 'SWE', name: 'Sweden', avatar: '🇸🇪', continent: 'Europe', tier: 2, profile: 'A Scandinavian nation with thousands of coastal islands and inland lakes...', detailedProfile: 'Sweden is known for its welfare state...', motto: 'För Sverige – i tiden', established: 'June 6, 1523', nationalDay: 'June 6', newYear: 'January 1', language: 'Swedish', ethnic_groups: ['Swedish', 'Finnish', 'Syrian'] },
    'CHE': { id: 'CHE', name: 'Switzerland', avatar: '🇨🇭', continent: 'Europe', tier: 2, persona: Personas.CHE_PERSONA, profile: 'A mountainous Central European country...', detailedProfile: 'Switzerland is known for its neutrality...', motto: 'Unus pro omnibus, omnes pro uno', established: 'August 1, 1291', nationalDay: 'August 1', newYear: 'January 1', language: 'German, French, Italian', ethnic_groups: ['Swiss', 'German', 'Italian'] },
    'SYR': { id: 'SYR', name: 'Syria', avatar: '🇸🇾', continent: 'Asia', tier: 3, profile: 'A country in Western Asia...', detailedProfile: 'Syria has been embroiled in a devastating civil war...', motto: 'وحدة، حرية، اشتراكية', established: 'April 17, 1946', nationalDay: 'April 17', newYear: 'January 1', language: 'Arabic', ethnic_groups: ['Arab', 'Kurd', 'Turkmen'] },
    'TWN': { id: 'TWN', name: 'Taiwan', avatar: '🇹🇼', continent: 'Asia', tier: 2, profile: 'An island in East Asia...', detailedProfile: 'Taiwan is a global leader in semiconductor manufacturing...', motto: 'N/A', established: 'October 10, 1911', nationalDay: 'October 10', newYear: 'Lunar New Year', language: 'Mandarin Chinese', ethnic_groups: ['Han (Hoklo, Hakka)', 'Indigenous peoples'] },
    'TZA': { id: 'TZA', name: 'Tanzania', avatar: '🇹🇿', continent: 'Africa', tier: 3, profile: 'An East African country known for its vast wilderness areas...', detailedProfile: 'Tanzania is home to Mount Kilimanjaro...', motto: 'Uhuru na Umoja', established: 'April 26, 1964', nationalDay: 'April 26', newYear: 'January 1', language: 'Swahili, English', ethnic_groups: ['Over 120 ethnic groups'] },
    'THA': { id: 'THA', name: 'Thailand', avatar: '🇹🇭', continent: 'Asia', tier: 2, profile: 'A Southeast Asian country. It\'s known for tropical beaches, opulent royal palaces, ancient ruins and ornate temples displaying figures of Buddha...', detailedProfile: 'Thailand is the only Southeast Asian country never to have been colonized by a European power...', motto: 'ชาติ ศาสนา พระมหากษัตริย์', established: '1238', nationalDay: 'December 5', newYear: 'Songkran (April 13-15)', language: 'Thai', ethnic_groups: ['Thai', 'Chinese'] },
    'TUR': { id: 'TUR', name: 'Turkey', avatar: '🇹🇷', continent: 'Asia', tier: 2, profile: 'A large peninsula that bridges the continents of Europe and Asia...', detailedProfile: 'Turkey has a unique cultural blend of Eastern and Western traditions...', motto: 'Egemenlik kayıtsız şartsız milletindir', established: 'October 29, 1923', nationalDay: 'October 29', newYear: 'January 1', language: 'Turkish', ethnic_groups: ['Turkish', 'Kurdish'] },
    'UGA': { id: 'UGA', name: 'Uganda', avatar: '🇺🇬', continent: 'Africa', tier: 3, profile: 'A landlocked country in East Africa...', detailedProfile: 'Uganda is known as the "Pearl of Africa"...', motto: 'For God and My Country', established: 'October 9, 1962', nationalDay: 'October 9', newYear: 'January 1', language: 'English, Swahili', ethnic_groups: ['Baganda', 'Banyankole', 'Basoga'] },
    'UKR': { id: 'UKR', name: 'Ukraine', avatar: '🇺🇦', continent: 'Europe', tier: 2, profile: 'A large country in Eastern Europe known for its Orthodox churches, Black Sea coastline and forested mountains...', detailedProfile: 'Ukraine is a major agricultural producer...', motto: 'Воля, злагода, добро', established: 'August 24, 1991', nationalDay: 'August 24', newYear: 'January 1', language: 'Ukrainian', ethnic_groups: ['Ukrainian', 'Russian'] },
    'ARE': { id: 'ARE', name: 'United Arab Emirates', avatar: '🇦🇪', continent: 'Asia', tier: 2, persona: Personas.ARE_PERSONA, profile: 'An Arabian Peninsula nation settled mainly along the Persian (Arabian) Gulf...', detailedProfile: 'The UAE is a federation of seven emirates...', motto: 'الله، الوطن، الرئيس', established: 'December 2, 1971', nationalDay: 'December 2', newYear: 'January 1', language: 'Arabic', ethnic_groups: ['Emirati', 'South Asian', 'Egyptian'] },
    'GBR': { id: 'GBR', name: 'United Kingdom', avatar: '🇬🇧', continent: 'Europe', tier: 1, persona: Personas.GBR_PERSONA, profile: 'A constitutional monarchy...', detailedProfile: 'The United Kingdom, made up of England, Scotland, Wales and Northern Ireland...', motto: 'Dieu et mon droit', established: 'May 1, 1707', nationalDay: 'Varies (King\'s Birthday)', newYear: 'January 1', language: 'English', ethnic_groups: ['White', 'Asian', 'Black'] },
    'USA': { id: 'USA', name: 'United States', avatar: '🇺🇸', continent: 'North America', tier: 1, persona: Personas.USA_PERSONA, profile: 'A global superpower...', detailedProfile: 'The United States is a federal republic of 50 states...', motto: 'In God We Trust', established: 'July 4, 1776', nationalDay: 'July 4', newYear: 'January 1', language: 'English', ethnic_groups: ['White', 'Hispanic', 'Black', 'Asian'] },
    'URY': { id: 'URY', name: 'Uruguay', avatar: '🇺🇾', continent: 'South America', tier: 3, profile: 'A South American country known for its verdant interior and beach-lined coast...', detailedProfile: 'Uruguay is considered one of the most socially progressive countries in Latin America...', motto: 'Libertad o Muerte', established: 'August 25, 1825', nationalDay: 'August 25', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['White'] },
    'UZB': { id: 'UZB', name: 'Uzbekistan', avatar: '🇺🇿', continent: 'Asia', tier: 3, profile: 'A Central Asian nation and former Soviet republic...', detailedProfile: 'Uzbekistan is known for its Silk Road cities...', motto: 'N/A', established: 'September 1, 1991', nationalDay: 'September 1', newYear: 'Nowruz (March 21)', language: 'Uzbek', ethnic_groups: ['Uzbek', 'Tajik', 'Kazakh', 'Russian'] },
    'VEN': { id: 'VEN', name: 'Venezuela', avatar: '🇻🇪', continent: 'South America', tier: 3, profile: 'A country on the northern coast of South America...', detailedProfile: 'Venezuela has the world\'s largest known oil reserves...', motto: 'Dios y Federación', established: 'July 5, 1811', nationalDay: 'July 5', newYear: 'January 1', language: 'Spanish', ethnic_groups: ['Mestizo', 'White', 'Black'] },
    'VNM': { id: 'VNM', name: 'Vietnam', avatar: '🇻🇳', continent: 'Asia', tier: 2, profile: 'A Southeast Asian country known for its beaches, rivers, Buddhist pagodas and bustling cities...', detailedProfile: 'Vietnam has a fast-growing economy...', motto: 'Độc lập – Tự do – Hạnh phúc', established: 'September 2, 1945', nationalDay: 'September 2', newYear: 'Tết (Lunar New Year)', language: 'Vietnamese', ethnic_groups: ['Kinh (Viet)', 'Tay', 'Thai', 'Muong'] },
    'ZMB': { id: 'ZMB', name: 'Zambia', avatar: '🇿🇲', continent: 'Africa', tier: 3, profile: 'A landlocked country in southern Africa...', detailedProfile: 'Zambia is known for Victoria Falls...', motto: 'One Zambia, One Nation', established: 'October 24, 1964', nationalDay: 'October 24', newYear: 'January 1', language: 'English', ethnic_groups: ['Bemba', 'Tonga', 'Chewa', 'Lozi'] },
    'ZWE': { id: 'ZWE', name: 'Zimbabwe', avatar: '🇿🇼', continent: 'Africa', tier: 3, profile: 'A landlocked country in southern Africa...', detailedProfile: 'Zimbabwe is known for its dramatic landscape...', motto: 'Unity, Freedom, Work', established: 'April 18, 1980', nationalDay: 'April 18', newYear: 'January 1', language: 'English, Shona, Ndebele', ethnic_groups: ['Shona', 'Ndebele'] },
};

export const G7_MEMBERS = ['CAN', 'FRA', 'DEU', 'ITA', 'JPN', 'GBR', 'USA'];
export const BRICS_MEMBERS = ['BRA', 'RUS', 'IND', 'CHN', 'ZAF', 'EGY', 'ETH', 'IRN', 'ARE'];
export const SCO_MEMBERS = ['CHN', 'IND', 'KAZ', 'KGZ', 'PAK', 'RUS', 'UZB', 'IRN'];
export const NATO_MEMBERS = ['ALB', 'BEL', 'BGR', 'CAN', 'HRV', 'CZE', 'DNK', 'EST', 'FIN', 'FRA', 'DEU', 'GRC', 'HUN', 'ISL', 'ITA', 'LVA', 'LTU', 'LUX', 'MNE', 'NLD', 'MKD', 'NOR', 'POL', 'PRT', 'ROU', 'SVK', 'SVN', 'ESP', 'TUR', 'GBR', 'USA', 'SWE'];
export const EU_MEMBERS = ['AUT', 'BEL', 'BGR', 'HRV', 'CYP', 'CZE', 'DNK', 'EST', 'FIN', 'FRA', 'DEU', 'GRC', 'HUN', 'IRL', 'ITA', 'LVA', 'LTU', 'LUX', 'MLT', 'NLD', 'POL', 'PRT', 'ROU', 'SVK', 'SVN', 'ESP', 'SWE'];
export const AU_MEMBERS = ['DZA', 'AGO', 'BEN', 'BWA', 'BFA', 'BDI', 'CMR', 'CAF', 'TCD', 'COM', 'EGY', 'GNQ', 'ETH', 'GAB', 'GMB', 'GHA', 'GIN', 'KEN', 'LSO', 'LBR', 'LBY', 'MDG', 'MWI', 'MLI', 'MRT', 'MUS', 'MAR', 'MOZ', 'NAM', 'NER', 'NGA', 'RWA', 'SEN', 'ZAF', 'TZA', 'UGA', 'ZMB', 'ZWE'];
export const ARAB_LEAGUE_MEMBERS = ['DZA', 'BHR', 'COM', 'DJI', 'EGY', 'IRQ', 'JOR', 'KWT', 'LBN', 'LBY', 'MRT', 'MAR', 'OMN', 'QAT', 'SAU', 'SYR', 'ARE'];
export const GCC_MEMBERS = ['BHR', 'KWT', 'OMN', 'QAT', 'SAU', 'ARE'];

export const BREAKING_NEWS_OPTIONS: NewsItem[] = [
    { id: 'news_1', title: 'Breakthrough in Fusion Energy Hailed as "New Dawn"', snippet: 'Scientists at a joint international lab have announced a sustained fusion reaction, producing net positive energy for the first time. The development could revolutionize the energy sector and climate change efforts.', source: 'Global Science Times' },
    { id: 'news_2', title: 'Central Banks Announce Coordinated Digital Currency Initiative', snippet: 'A consortium of the world\'s largest central banks is launching a pilot program for a cross-border digital currency, aiming to streamline international trade and challenge the dominance of existing systems.', source: 'Financial World News' },
    { id: 'news_3', title: 'Asteroid Mining Treaty Negotiations Begin at UN', snippet: 'Delegates from over 50 nations have gathered to draft a legal framework for the exploitation of resources from asteroids and other celestial bodies, a topic of growing economic and strategic importance.', source: 'Interplanetary Chronicle' },
    { id: 'news_4', title: 'Global Supply Chains Face Disruption from New Shipping Regulations', snippet: 'Strict new environmental regulations for maritime shipping are set to take effect, with experts predicting significant short-term disruptions and increased costs for international trade as carriers adapt.', source: 'Trade Winds Daily' },
    { id: 'news_5', title: 'Major Undersea Data Cable Severed in Disputed Waters', snippet: 'A critical fiber optic cable connecting two continents has been mysteriously cut, leading to widespread internet outages and accusations of state-sponsored sabotage. Naval assets are being deployed to the area.', source: 'Network Security Today' },
    { id: 'news_6', title: 'Drought Leads to Unprecedented Global Grain Shortage', snippet: 'Severe droughts in several key breadbasket nations have caused a critical shortage in the global grain supply. Food prices are skyrocketing, and humanitarian organizations are warning of an impending famine in vulnerable regions.', source: 'World Food Program Report' }
];

export const EVENT_KNOWLEDGE_BASE: NewsItem[] = [
    { id: 'kb_1', title: 'Global Semiconductor Supply Chain Disruption', snippet: 'A series of factory shutdowns and logistical bottlenecks over the past year have caused a global shortage in semiconductors, impacting everything from cars to consumer electronics. Major tech powers are now scrambling to secure their supply chains.', source: 'World Economic Review', tags: ['economy', 'technology', 'supply_chain'], involved_countries: ['USA', 'CHN', 'JPN', 'KOR', 'DEU', 'TWN'] },
    { id: 'kb_2', title: 'Arctic Sea Route Opens for Record Duration', snippet: 'Climate change has led to the Northern Sea Route being ice-free for an unprecedented period this year, intensifying geopolitical competition over the new shipping lane and access to Arctic resources.', source: 'Polar Politics Journal', tags: ['geopolitics', 'climate', 'trade', 'security'], involved_countries: ['RUS', 'CAN', 'USA', 'CHN', 'NOR', 'DNK'] },
    { id: 'kb_3', title: 'Sahel Region Faces Escalating Security Crisis', snippet: 'A wave of instability and extremist violence is spreading across the Sahel region of Africa, causing widespread displacement and threatening the stability of multiple governments. International responses have been fragmented.', source: 'Global Security Watch', tags: ['security', 'conflict', 'africa'], involved_countries: ['FRA', 'BFA', 'MLI', 'NER', 'DZA', 'RUS'] },
    { id: 'kb_4', title: 'Contention over "Green Hydrogen" Standards', snippet: 'As nations rush to develop green hydrogen, a major diplomatic disagreement is brewing over what constitutes "green." Export-focused nations with vast renewables (like Chile, Australia) are pushing for looser standards than import-focused industrial blocs (like the EU).', source: 'Renewable Future Magazine', tags: ['economy', 'climate', 'energy', 'technology'], involved_countries: ['DEU', 'AUS', 'CHL', 'JPN', 'SAU'] }
];

export const RANDOM_EVENT_TEMPLATES: NewsItem[] = [
    { id: 'rand_1', title: '[COUNTRY_A] Announces Major Breakthrough in AI-Powered Drug Discovery', snippet: 'The national research institute of [COUNTRY_A] has unveiled a new AI platform that dramatically accelerates the creation of new medicines, potentially shifting the balance of power in the global pharmaceutical industry.', source: 'Simulated News Network', isFabricated: true },
    { id: 'rand_2', title: 'Severe Epidemic Breaks Out in [REGION], Borders Sealed', snippet: 'An unknown and highly contagious virus has been reported in the [REGION] region, prompting neighboring countries like [COUNTRY_A] and [COUNTRY_B] to close their borders and halt all travel, causing regional chaos.', source: 'Simulated News Network', isFabricated: true },
    { id: 'rand_3', title: 'Massive Cyberattack Cripples Global Financial Markets', snippet: 'A sophisticated cyberattack of unknown origin has targeted major stock exchanges and banking systems worldwide. Trading has been halted as powers like [COUNTRY_A] and [COUNTRY_B] accuse each other of digital warfare.', source: 'Simulated News Network', isFabricated: true },
    { id: 'rand_4', title: 'Discovery of Massive Rare Earth Mineral Deposit in [COUNTRY_A]', snippet: 'Geologists in [COUNTRY_A] have confirmed the discovery of one of the world\'s largest untapped reserves of rare earth minerals, critical for modern technology. The find could challenge [COUNTRY_B]\'s long-standing dominance in the strategic sector.', source: 'Simulated News Network', isFabricated: true }
];

export const TRANSLATIONS = {
    en: {
        chats: 'Chats',
        directory: 'Directory',
        motto: 'Motto',
        language: 'Language',
        ethnicGroups: 'Ethnic Groups',
        shortTermGoal: 'Short-Term Goal',
        longTermGoal: 'Long-Term Goal',
        chat: 'Chat',
        settings: 'Settings',
        theme: 'Theme',
        scale: 'AI Chat Intensity',
        intensity: { simple: 'Simple', medium: 'Medium', high: 'High', intense: 'Intense' },
        close: 'Close',
    },
    zh: {
        chats: '聊天',
        directory: '通讯录',
        motto: '格言',
        language: '语言',
        ethnicGroups: '主要族群',
        shortTermGoal: '短期目标',
        longTermGoal: '长期目标',
        chat: '聊天',
        settings: '设置',
        theme: '主题',
        scale: 'AI聊天激烈程度',
        intensity: { simple: '简单', medium: '中等', high: '高度', intense: '激烈' },
        close: '关闭',
    },
};